services:
  - type: web
    name: tcs-nqt-2026
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://auto:InnEb6gzJcghXcAGPlDW07Z5QVYbapGF@dpg-d6hasvrh46gs73e3m2b0-a/auto_ydvo
      - key: PYTHON_VERSION
        value: 3.11.0
